Controllers/BlogPostsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShadowBlog.Data;
using ShadowBlog.Models;
using ShadowBlog.Services.Interfaces;
using ShadowBlog.Enums;
using Microsoft.AspNetCore.Authorization;
using ShadowBlog.Services;
using X.PagedList;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;

namespace ShadowBlog.Controllers
{
    public class BlogPostsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IImageService _imageService;
        private readonly ISlugService _slugService;
        private readonly SearchService _searchService;
        private readonly UserManager<BlogUser> _userManager;

        public BlogPostsController(ApplicationDbContext context,
                                    IImageService imageService,
                                    ISlugService slugService,
                                    SearchService searchService,
                                    UserManager<BlogUser> userManager)
        {
            _context = context;
            _imageService = imageService;
            _slugService = slugService;
            _searchService = searchService;
            _userManager = userManager;
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> SearchPosts(int? page, string searchTerm)
        {
            var pageNumber = page ?? 1;
            var pageSize = 5;
            ViewData["SearchTerm"] = searchTerm;

            var blogPosts = await _searchService.SearchAsync(searchTerm);
            if (blogPosts.Count == 0)
            {
                ViewData["Message"] = "No Posts Found Matching your search term. Please try searching something else";
            }

            return View("SearchPosts", await blogPosts.ToPagedListAsync(pageNumber, pageSize));
        }

        public async Task<IActionResult> ChildIndex(int blogId, int? page)
        {
            //I don't want to get all of the BlogPosts....
            //I want to get all of the BlogPosts where the BlogId = blogId
            //Also...I only want to grab production ready BlogPosts
            var pageNumber = page ?? 1;
            var pageSize = 5;

            var applicationDbContext = _context.BlogPosts
                .Include(b => b.Blog)
                .Where(b => b.ReadyStatus == ReadyState.ProductionReady && b.BlogId == blogId)
                .OrderByDescending(b => b.Created);

            var blogPosts = await applicationDbContext.ToPagedListAsync(pageNumber, pageSize);

            return View(blogPosts);
        }

        // GET: BlogPosts
        public async Task<IActionResult> Index(int? page)
        {
            var pageNumber = page ?? 1;
            var pageSize = 5;

            var applicationDbContext = _context.BlogPosts
                .Include(b => b.Blog)
                .Where(b => b.ReadyStatus == ReadyState.ProductionReady)
                .OrderByDescending(b => b.Created);

            var blogPosts = await applicationDbContext.ToPagedListAsync(pageNumber, pageSize);

            return View(blogPosts);
        }

        public async Task<IActionResult> Preview()
        {
            var blogPosts = _context.BlogPosts
               .Include(b => b.Blog)
               .Where(b => b.ReadyStatus == ReadyState.InPreview)
               .OrderByDescending(b => b.Created);

            return View("Index", await blogPosts.ToListAsync());
        }

        // GET: BlogPosts/Details/5

        public async Task<IActionResult> Details(string slug)
        {
            if (string.IsNullOrEmpty(slug))
            {
                return NotFound();
            }

            var blogPost = await _context.BlogPosts
                .Include(b => b.Blog)
                .Include(b => b.Tags)
                .Include(b => b.Comments)
                    .ThenInclude(c => c.Moderator)
                .Include(b => b.Comments)
                    .ThenInclude(c => c.BlogUser)
                .FirstOrDefaultAsync(m => m.Slug == slug);

            if (blogPost == null)
            {
                return NotFound();
            }

            return View(blogPost);
        }

        public async Task<IActionResult> TagIndex(string tag, int? page)
        {
            //Start with my pageing data
            var pageNumber = page ?? 1;
            var pageSize = 6;

            var allBlogPostIds = _context.Tags.Where(t => t.Text.ToLower() == tag.ToLower())
                                              .Select(t => t.BlogPostId);

            var blogPosts = await _context.BlogPosts
                                        .Where(b => allBlogPostIds.Contains(b.Id))
                                        .OrderByDescending(b => b.Created)
                                        .ToPagedListAsync(pageNumber, pageSize);

            ViewData["Tag"] = tag;
            return View(blogPosts);
        }

        //GET: BlogPosts/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create(int? blogId)
        {
            if (blogId is not null)
            {
                BlogPost newBlogPost = new()
                {
                    BlogId = (int)blogId
                };

                return View(newBlogPost);
            }

            ViewData["BlogId"] = new SelectList(_context.Blogs, "Id", "Name");
            return View();
        }

        // POST: BlogPosts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BlogId,Title,Abstract,Content,ReadyStatus,Image")] BlogPost blogPost, List<string> tagValues)
        {
            if (ModelState.IsValid)
            {
                //Let's create and check the slug for uniqueness
                var slug = _slugService.UrlFriendly(blogPost.Title);
                if (!_slugService.IsUnique(slug))
                {
                    //Create a custom Model Error and complain to the user
                    ModelState.AddModelError("Title", "Error: Title has already been used.");
                    return View(blogPost);
                }
                else
                {
                    blogPost.Slug = slug;
                }

                //Either record the incoming image or use the default image
                if (blogPost.Image is not null)
                {
                    if (!_imageService.ValidImage(blogPost.Image))
                    {
                        if (!_imageService.ValidType(blogPost.Image))
                        {
                            ModelState.AddModelError("Image", "Please choose a valid image type.");
                            return View(blogPost);
                        }
                        else
                        {
                            ModelState.AddModelError("Image", "Please choose a valid image size.");
                            return View(blogPost);
                        }
                    }
                    else
                    {
                        blogPost.ImageData = await _imageService.EncodeImageAsync(blogPost.Image);
                        blogPost.ImageType = _imageService.ContentType(blogPost.Image);
                    }
                }
                else
                {
                    blogPost.ImageData = await _imageService.EncodeImageAsync("blogPostDefaultImage.png");
                    blogPost.ImageType = "png";
                }

                blogPost.Created = DateTime.Now;

                //TODO: Add code in here to generate the Slug from the Title

                _context.Add(blogPost);
                await _context.SaveChangesAsync();

                foreach (var tag in tagValues)
                {
                    _context.Add(new Tag()
                    {
                        BlogPostId = blogPost.Id,
                        Text = tag
                    });
                }

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            ViewData["BlogId"] = new SelectList(_context.Blogs, "Id", "Name", blogPost.BlogId);
            return View(blogPost);
        }

        // GET: BlogPosts/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogPost = await _context.BlogPosts.Include(p => p.Tags).FirstOrDefaultAsync(p => p.Id == id);

            if (blogPost == null)
            {
                return NotFound();
            }
            ViewData["TagValues"] = string.Join(",", blogPost.Tags.Select(t => t.Text));
            ViewData["BlogId"] = new SelectList(_context.Blogs, "Id", "Description", blogPost.BlogId);
            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BlogId,Title,Abstract,Content,Created,ReadyStatus,ImageData,ImageType,Slug,Image")] BlogPost blogPost, List<string> tagValues)
        {
            if (id != blogPost.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using ShadowBlog.Data;
using ShadowBlog.Models;
using ShadowBlog.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ShadowBlog.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly IEmailSender _emailService;
        private IConfiguration _configuration;

        public HomeController(ILogger<HomeController> logger,
                                ApplicationDbContext context,
                                IEmailSender emailService,
                                IConfiguration configuration)
        {
            _logger = logger;
            _context = context;
            _emailService = emailService;
            _configuration = configuration;
        }

        public async Task<IActionResult> Index()
        {
            PostCardsViewModel newestCards = new()
            {
                MainCard = await _context.Blogs.OrderByDescending(b => b.Created).FirstOrDefaultAsync(),
                SideCards = await _context.Blogs.OrderByDescending(b => b.Created).ToListAsync(),
                MainPostCard = await _context.BlogPosts.OrderByDescending(b => b.Created).FirstOrDefaultAsync(),
                SidePostCards = await _context.BlogPosts.OrderByDescending(b => b.Created).ToListAsync()
            };
            HomeIndexViewModel blogsvm = new()
            {
                Blogs = await _context.Blogs.ToListAsync(),
                MostRecentBlog = await _context.Blogs.OrderByDescending(b => b.Created).FirstOrDefaultAsync(),
                MostRecentPost = await _context.BlogPosts.OrderByDescending(b => b.Created).FirstOrDefaultAsync(),
                OldestPosts = await _context.BlogPosts.OrderBy(p => p.Created).ToListAsync(),
                MainOldestPost = await _context.BlogPosts.OrderBy(p => p.Created).FirstOrDefaultAsync(),
                MainOldestBlog = await _context.Blogs.OrderBy(p => p.Created).FirstOrDefaultAsync(),
                OldestBlogs = await _context.Blogs.OrderBy(b => b.Created).ToListAsync(),

                NewestCards = newestCards,
            };

            return View( blogsvm);
        }

        public IActionResult ContactMe()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ContactMe(string name, string email, string phone, string message)
        {
            var subject = $"{name} has reached out to you from the ShadowBlog Application";

            var body = $"{message}.<br/><br/>{name} can be called at {phone} or emailed at {email} if follow up is required.";

            var myEmail = _configuration["SmtpSettings:Email"];
            await _emailService.SendEmailAsync(myEmail, subject, body);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Newsletter(string email)
        {
            var subject = $"Thank you for Subscribing to our Newsletter";

            var body = $"You will get the latest updates on our Blog!";

            
            await _emailService.SendEmailAsync(email, subject, body);
            return RedirectToAction(nameof(Index));
        }


        public IActionResult AboutMe()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        
       
       
    }
}

Views/Home/ContactMe.cshtml
@using ShadowBlog.Services.Interfaces
@inject IImageService _imageService
<!--=====================================-->
<!--=           Category Start        	=-->
<!--=====================================-->
<!--=====================================-->
<!--=        Contact Page Start        	=-->
<!--=====================================-->

@{
    ViewData["Title"] = "Contact";
}

<section class="inner-section">
    <div class="container">
        <div class="row gutters-40">
            <div class="col-xl-9 col-lg-8">
                <div class="contact-page">

                    @*<div class="about-content">
                            <div class="heading-layout3">
                                <h3 class="heading-title">About Gamex</h3>
                            </div>
                            <p>Frium has been the industry's standard dummy text ever since thewhen an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only fiveIpsum has been the industry's standard dummy text ever since printer took.</p>
                        </div>*@

                    <div class="contact-form  card">
                        <div class="heading-layout3">
                            <h3 class="heading-title mt-3 p-3">Send Us A Message</h3>
                        </div>
                        <form asp-action="ContactMe" asp-controller="Home" class="card-body">
                            <div class="row gutters-15">
                                <div class="col-lg-4 form-group">
                                    <input type="text" placeholder="Name" class="form-control" name="name" data-error="Name field is required" required>
                                    <div class="help-block with-errors"></div>
                                </div>
                                <div class="col-lg-4 form-group">
                                    <input type="email" placeholder="E-mail" class="form-control" name="email" data-error="Email field is required" required>
                                    <div class="help-block with-errors"></div>
                                </div>
                                <div class="col-lg-4 form-group">
                                    <input type="text" placeholder="Phone" class="form-control" name="phone" data-error="Phone field is required" required>
                                    <div class="help-block with-errors"></div>
                                </div>
                                <div class="col-12 form-group">
                                    <textarea placeholder="Message" class="textarea form-control" name="message" rows="7" cols="20" data-error="Message field is required" required></textarea>
                                    <div class="help-block with-errors"></div>
                                </div>
                                <div class="col-12 form-group">
                                    <button type="submit" class="submit-btn">SUBMIT NOW</button>
                                </div>
                            </div>
                            <div class="form-response"></div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-4 sidebar-widget">
                <div class="widget widget-search">
                    <form asp-action="SearchPosts" asp-controller="BlogPosts">
                        <div class="input-group stylish-input-group">
                            <input type="text" name="searchTerm" class="form-control" placeholder="Search Story . . .">
                            <span class="input-group-addon">
                                <button type="submit">
                                    <span class="flaticon-search" aria-hidden="true"></span>
                                </button>
                            </span>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!--=====================================-->
<!--=            Social Start           =-->
<!--=====================================-->
<section class="social-box-wrap">
    <div class="container-fluid full-width">
    </div>
</section>
<!--=====================================-->
<!--=            Footer Start           =-->
<!--=====================================-->